spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC
    username: zylai(S5q0WQQD0ZMSnSUptirN3TdcpkLBV2elIq1rEzWqrO4QVAOqPV7vOqwVsV8FI8lb)
    password: zylai(rZ8qGFdZIxNvmOM5nFcQVLQ2lavkDgSV0bwK40R0mU6VGFTaYAkbh67YKlTDPJQ+)
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet: #监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: true
      web-stat-filter: #监控web
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        url-pattern: /*
      aop-patterns: com.atguigu.boot
      # 开启的功能
      filters: stat,wall
      #      在这里配置具体的属性
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  jdbc:
    template:
      query-timeout: 3
  redis:
    host: 82.157.140.177
    port: 6379
    password: zylai(7AuR89mdpV5u4uMeg9nvNwX78LCzW64sCpb7OOPSL4FhbpGzrbUktIXcrVanH+CP)
#    password: 123321
    client-name: lettuce
    lettuce:
      pool:
        max-active: 8
        min-idle: 0

#server:
#  error:
#    path: /error

#配置mybatis的规则
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*xml
  configuration:
    map-underscore-to-camel-case: true
jasypt:
  encryptor:
#    加密密匙，从系统的环境变量中获取
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    property:
      prefix: zylai(
      suffix: )
